### ISSUE TITLE
Feat: Import old repo from https://github.com/thenocturnaldevgypsy/thenocturnaldevgypsy to https://github.com/thenocturnaldevgypsy-io/thenocturnaldevgypsy-io

### ISSUE THREAD

**Issue by thenocturnaldevgypsy-io** [thenocturnaldevgypsy-io/thenocturnaldevgypsy-io#1]
Feat: Import my old repo from https://github.com/thenocturnaldevgypsy to https://github.com/thenocturnaldevgypsy-io

Since my 10 year old GitHub account @thenocturnaldevgypsy got "flagged" by GitHub for no apparent reason (GitHub even not responding to my support ticket), I am recreating my old repos to the newly created GitHub account @thenocturnaldevgypsy-io . This is also a good practice/excuse to use GitHub Projects in preparation for most of my freelance work requirements.

I'm just thankful that I still have access to my old account in order to clone the content to my local Git,

Old repo: https://github.com/thenocturnaldevgypsy/thenocturnaldevgypsy
New repo: https://github.com/thenocturnaldevgypsy-io/thenocturnaldevgypsy-io

**Comment by thenocturnaldevgypsy-io** [comment]
Progress: for setting up the GitHub and WakaTime stats.
- Created the needed PAT token for the `repo` and `user` tracking
- Forked https://github.com/anuraghazra/github-readme-stats, deployed to Vercel to all tracking with my Private Repos stats (https://vercel.com/thenocturnaldevgypsys-projects/github-stats/8KkJ3dnznhXY5gqcR6GbQ1Uq8PbH)

**Comment by thenocturnaldevgypsy-io** [comment]
**Additional notes**: Can't run https://github.com/anmol098/waka-readme-stats , currently getting the errors due to lack of activities here at GitHub (?) since it's a new profile. Will revisit this later once done with importing all public and private repos, and will decide if I need to create a Bug ticket for this to work on it further.
```
Run anmol098/waka-readme-stats@master
/usr/bin/docker run --name wakareadmestatswakareadmestatsmaster_63221d --label be5ff0 --workdir /github/workspace --rm -e "INPUT_WAKATIME_API_KEY" -e "INPUT_GH_TOKEN" -e "INPUT_SYMBOL_VERSION" -e "INPUT_SHOW_PROJECTS" -e "INPUT_SHOW_LINES_OF_CODE" -e "INPUT_SHOW_LOC_CHART" -e "INPUT_SHOW_OS" -e "INPUT_SHOW_UPDATED_DATE" -e "INPUT_UPDATED_DATE_FORMAT" -e "INPUT_SHOW_TOTAL_CODE_TIME" -e "INPUT_SHOW_PROFILE_VIEWS" -e "INPUT_SHOW_COMMIT" -e "INPUT_SHOW_DAYS_OF_WEEK" -e "INPUT_SHOW_LANGUAGE" -e "INPUT_SHOW_EDITORS" -e "INPUT_SHOW_LANGUAGE_PER_REPO" -e "INPUT_SHOW_SHORT_INFO" -e "INPUT_LOCALE" -e "INPUT_SHOW_TIMEZONE" -e "INPUT_SECTION_NAME" -e "INPUT_PULL_BRANCH_NAME" -e "INPUT_PUSH_BRANCH_NAME" -e "INPUT_COMMIT_BY_ME" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_COMMIT_USERNAME" -e "INPUT_COMMIT_EMAIL" -e "INPUT_COMMIT_SINGLE" -e "INPUT_IGNORED_REPOS" -e "INPUT_DEBUG_LOGGING" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/thenocturnaldevgypsy-io/thenocturnaldevgypsy-io":"/github/workspace" wakareadmestats/waka-readme-stats:master
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 230, in <module>
    run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line 217, in main
    stats = await get_stats()
            ^^^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line 193, in get_stats
    stats += f"{make_language_per_repo_list(repositories)}\n\n"
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/waka-readme-stats/graphics_list_formatter.py", line 141, in make_language_per_repo_list
    top_language = max(list(language_count.keys()), key=lambda x: language_count[x]["count"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```
